Repository netlify/dusty-domains, pull requests merged in 2021-12, with the labels that each got.

#42 Add charities list
  _includes/components/charities.css
  _includes/components/companies.css
  _includes/layout.njk
  index.njk
  static/logo-black-girls-code.svg
  static/logo-code2040.jpg
  static/logo-resilient-coders.png
  static/logo-stem-tank.svg
Labels: type: design, type: content

#45 Make it more clear when the deadline is
  index.njk
Labels: type: content

#46 Create way for partners to include a link
  _includes/components/charities.css
  _includes/components/companies.css
  index.njk
Labels: type: design, type: content

#48 Add two partners, update totals
  _includes/components/companies.css
  index.njk
  static/logo-cockroachDB.png
  static/logo-remix.svg
  thanks.njk
Labels: type: content

#47 Additional error handling for submission form
  netlify/functions/upload.js
  static/index.js
Labels: type: bug

#50 Update showcase presentation
  index.njk
  netlify/plugins/airtable-feed/index.js
  thanks.njk
Labels: type: feature

#51 Update partner list
  _includes/components/companies.css
  _includes/components/type.css
  index.njk
  static/logo-sanity.png
  thanks.njk
Labels: type: design, type: content

#53 Update partners
  _includes/components/companies.css
  index.njk
  static/logo-new-relic.svg
  thanks.njk
Labels: type: content

#55 add Domainr + update totals
  _includes/components/companies.css
  index.njk
  static/logo-domainr.svg
  thanks.njk
Labels: type: content

#56 Fix positioning so showcase doesn’t shift on hover
  _includes/components/showcase.css
  index.njk
  static/index.js
Labels: type: design

#57 feat: add SingleStore
  index.njk
  static/logo-singlestore.svg
  thanks.njk
Labels: type: content

#58 Add MUX and update totals
  index.njk
  static/logo-mux.png
  thanks.njk
Labels: type: content

#59 Add singlestore link + a bit of style tweaking
  _includes/components/companies.css
  index.njk
Labels: type: design, type: content

#60 Add New Relic resource link
  _includes/components/companies.css
  index.njk
Labels: type: content

#62 Feature/thermometer
  _includes/components/companies.css
  _includes/components/progress-meter.css
  _includes/components/progress-meter.njk
  _includes/layout.njk
  index.njk
  netlify/functions/update.js
  static/index.js
  yarn.lock
Labels: type: feature, type: design, type: content
